[tool.poetry]
name = "commonroad-scenario-factory"
version = "0.1.0"
description = "Automated scenario generation for CommonRoad based on SUMO traffic simulations."
authors = ["Florian Finkeldei <florian.finkeldei@tum.de>"]
readme = "README.md"
packages = [{include = "scenario_factory"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
commonroad-io = "^2024.1"
commonroad-drivability-checker = "^2024.1"
libsumo = "^1.19.0"
pandas = "^2.0"
commonroad-scenario-designer = "^0.8.1"
sumocr = "^2024.1"
scikit-learn = "^1.3.2"
osmium = ">=2.16.0"
pyproj = "^3.6.1"
eclipse-sumo = "^1.19.0"
click = "^8.1.7"
multiprocess = "^0.70.16"

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^7.4.4"
coverage = {version = "^7.5.3", extras = ["toml"] }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.coverage.run]
source = ["scenario_factory"]

[tool.poetry.scripts]
scenario-factory = "scenario_factory.cli:generate"

[[tool.mypy.overrides]]
module = "scenario_factory.scenario_features.*"
ignore_errors = true
