[tool.poetry]
name = "commonroad-scenario-factory"
version = "0.1.0"
description = "Automated scenario generation for CommonRoad based on SUMO traffic simulations."
authors = ["Florian Finkeldei <florian.finkeldei@tum.de>"]
readme = "README.md"
packages = [{include = "scenario_factory"}]

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[tool.poetry.dependencies]
python = "~3.10" # Constraint is given by commonroad-labeling
commonroad-io = ">=2024.1"
commonroad-drivability-checker = "^2024.1"
commonroad-scenario-designer = "^0.8.2"
commonroad-labeling = { git = "git@gitlab.lrz.de:cps/commonroad/automatic-scenario-labeling.git", rev="c4b1f19fdb9548655cf4703ab5c2c4a43314578f"}
opentrafficsim = { version = "1.7.5", source = "test" }
crots = { git = "git@gitlab.lrz.de:cps/commonroad/cr-ots-interface.git", rev = "31feb24680295bc846f8873dd10ebcc79caae83d"}
sumocr = "^2024.1"
osmium = ">=2.16.0"
pyproj = "^3.6.1"
iso3166 = "^2.0"
libsumo = "^1.19"
pandas = "^2.0"
scikit-learn = "^1.3"
eclipse-sumo = "^1.19"
click = "^8.1"
multiprocess = "^0.70"
typing-extensions = "^4.12.2"


[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^7.4.4"
coverage = {version = "^7.5.3", extras = ["toml"] }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.coverage.run]
source = ["scenario_factory"]

[tool.poetry.scripts]
scenario-factory = "scenario_factory.cli:generate"
globetrotter = "scenario_factory.cli:globetrotter"

[[tool.mypy.overrides]]
module = "scenario_factory.scenario_features.*"
ignore_errors = true
