[tool.poetry]
name = "commonroad-scenario-factory"
version = "0.1.0"
description = "Automated scenario generation for CommonRoad based on SUMO traffic simulations."
authors = ["Florian Finkeldei <florian.finkeldei@tum.de>"]
readme = "README.md"
packages = [{include = "scenario_factory"}]

[tool.poetry.dependencies]
python = "^3.10"
commonroad-io = {git = "https://github.com/CommonRoad/commonroad-io.git", rev = "develop"}
commonroad-drivability-checker = "^2023.1"
libsumo = "^1.19.0"
pandas = "^2.0"
commonroad-scenario-designer = {git = "git@gitlab.lrz.de:cps/commonroad/commonroad-scenario-designer.git", branch = "develop"}
sumocr = "^2023.4"
scikit-learn = "^1.3.2"
osmium = ">=2.16.0"
pyproj = "^3.6.1"
eclipse-sumo = "^1.19.0"

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^7.4.4"
coverage = {version = "^7.5.3", extras = ["toml"] }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.coverage.run]
source = ["scenario_factory"]
