stages:
  - linting
  - testing

before_script:
  - echo $SUMO_HOME
  - apt-get update
  - apt-get install -y python3.10 python3-pip git
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  - poetry install --with tests

pre_commit:
  stage: linting
  image: python:3.10
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

main_testing:
  stage: testing
  image: gitlab.lrz.de:5005/cps/commonroad/scenario-factory
  script:
    - poetry run coverage run -m pytest
    - poetry run coverage report -m || true
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  needs: []
