stages:
  - linting
  - main_pipeline_test
  - unit_test
  - deploy

before_script:
  - echo $SUMO_HOME
  - apt-get install -y python3.10 python3-pip git
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  - poetry install

format_checking:
  stage: linting
  image: python:3.10
  script:
    - pip install black
    - black --check .
  allow_failure: true

main_pipeline_testing:
  stage: main_pipeline_test
  image: gitlab.lrz.de:5005/cps/commonroad/sumocr-scenario-generation
  script:
    - cd files
    - poetry run python n1_bounding_box_coordinates.py
    - poetry run python n2_osm_map_extraction.py
    - poetry run python n3_conversion_to_commonroad.py
    - poetry run python n4_globetrotter.py
    - poetry run python n5_scenario_generation.py
    - echo $(osmium --version)
  needs: []

unit_testing:
  stage: unit_test
  image: gitlab.lrz.de:5005/cps/commonroad/sumocr-scenario-generation
  script:
    - cd scripts
    - poetry run python assign_tags.py
